global:
  scrape_interval: 30s
  scrape_timeout: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: "blackbox"
    scrape_interval: 120s
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - enspire_api_kellanova,api.enspire.me/v2/user/app
          - enspire_api_dollargeneral, https://api.enspire.me/v2/user/app
          - enspire_api_michelin, https://api.enspire.me/v2/user/app
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*),.*$
        replacement: $1
        target_label: __param_module
      - source_labels: [__address__]
        regex: .*,(.*)$
        replacement: $1
        target_label: instance
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
